name:                haskell
version:             0.1.0.0
github:              "timofurrer/haskell"
license:             BSD-3-Clause
author:              "Timo Furrer"
maintainer:          "tuxtimo@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/timofurrer/haskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- unordered-containers
- hashable
- split
- data-clist
- parsec
- vector
- hashmap
- digits
- heap
- bytestring
- cryptonite

default-extensions:
- TupleSections
- DeriveGeneric
- ScopedTypeVariables
- FlexibleContexts

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell

tests:
  haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell
    - hspec
